# Generated by Django 5.2.8 on 2025-11-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Kategória',
                'verbose_name_plural': 'Kategóriák',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_embedding', models.BooleanField(default=False)),
                ('auto_anon', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tudásbázis beállítások',
                'verbose_name_plural': 'Tudásbázis beállítások',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='knowledge.knowledgecategory')),
            ],
            options={
                'verbose_name': 'Tudáselem',
                'verbose_name_plural': 'Tudáselemek',
                'ordering': ['-created_at'],
            },
        ),
    ]
