# Generated by Django 5.2.8 on 2025-11-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='knowledgeitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
