# Generated by Django 5.2.8 on 2025-11-14 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgecategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='Chunk sorszáma (0-al kezdődő).')),
                ('content', models.TextField(help_text='A chunk szöveges tartalma.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgeitem')),
            ],
            options={
                'verbose_name': 'Tudás-chunk',
                'verbose_name_plural': 'Tudás-chunkok',
                'ordering': ['item', 'index'],
                'unique_together': {('item', 'index')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(help_text='Embedding vektor float listaként.')),
                ('model_name', models.CharField(default='text-embedding-3-small', help_text='Embedding generálásához használt modell neve.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='knowledge.knowledgechunk')),
            ],
            options={
                'verbose_name': 'Embedding',
                'verbose_name_plural': 'Embeddingek',
            },
        ),
    ]
