# Generated by Django 5.2.8 on 2025-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_knowledgecategory_description_knowledgechunk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='is_embedded',
            field=models.BooleanField(default=False, help_text='Jelzi, hogy a chunk rendelkezik-e már embedding adattal.'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='anonymized_content',
            field=models.TextField(blank=True, help_text='Anonimizált (PII-mentesített) tartalom, amelyen a RAG pipeline dolgozik.', null=True),
        ),
    ]
